# Generated by Django 4.1 on 2023-12-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0004_add_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='authors',
        ),
    ]
