# Generated by Django 4.1 on 2023-12-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themes',
            old_name='theme',
            new_name='title',
        ),
    ]
