# Generated by Django 4.1 on 2023-12-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='class_id',
            new_name='class_fk',
        ),
        migrations.RenameField(
            model_name='testresults',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='testresults',
            old_name='test_id',
            new_name='test',
        ),
    ]
