# Generated by Django 4.1 on 2023-12-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
